version: 2
builds:
  - id: linux-amd64
    main: ./
    binary: gpu-metrics-agent
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
      - -v
    ldflags:
      # https://goreleaser.com/customization/build/#reproducible-builds
      # {{.CommitDate}} is the date of the commit to make builds reproducible.
      - -X main.version={{.Version}} -X main.commit={{.FullCommit}} -X main.date={{.CommitDate}} -X main.goArch=amd64
    tags:
      - osusergo
      - netgo
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- trimprefix .Version "v" }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
    format: binary
    format_overrides:
      - goos: windows
        format: zip
    files:
      - 'LICENSE*'
      - 'README*'
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Branch }}-{{ .ShortCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: polarsignals
    name: gpu-metrics-agent
  prerelease: auto
  draft: false
  name_template: '{{ .Tag }}'
dockers:
- image_templates: ["ghcr.io/polarsignals/{{ .ProjectName }}:{{ .Tag }}-amd64"]
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --pull
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://polarsignals.com
  - --label=org.opencontainers.image.source=https://github.com/polarsignals/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Tag }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0
docker_manifests:
- name_template: ghcr.io/polarsignals/{{ .ProjectName }}:{{ .Tag }}
  image_templates:
  - ghcr.io/polarsignals/{{ .ProjectName }}:{{ .Tag }}-amd64
- name_template: ghcr.io/polarsignals/{{ .ProjectName }}:latest
  image_templates:
  - ghcr.io/polarsignals/{{ .ProjectName }}:{{ .Tag }}-amd64
